name: Integracion continua con node.js

on:
  push:
    branches: [master]

jobs:
  ci_to_master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: running npm ci
      - run: npm ci
      - run: node --version
      - run: npm test
      - run: npm run dev



    